### ISSUE TITLE
Lesson 3 - Unable to untar IMDB urls

### ISSUE THREAD

**Issue by rbarman** [fastai/course-v3#243]
I am unable to untar the IMDB urls on a Kaggle kernal

- URLs.IMDB_SAMPLE : http://files.fast.ai/data/examples/imdb_sample
- URLs.IMDB : https://s3.amazonaws.com/fast-ai-nlp/imdb

```
from fastai.text import *
imdb = untar_data(URLs.IMDB)
```
Results in 
ConnectionError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /fast-ai-nlp/imdb.tgz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f82298ee5c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

It seems that the links are broken. Or is there something that I am missing?

**Comment by stas00** [comment]
The links ain't no broken. Especially since you have the same problem with 2 unrelated webservers. It is an issue with your DNS on your client. Not a fastai issue.

You can diagnose by trying to download it with other tools, curl or wget. just remember to add `.tgz` to the url when you take it to other tools, so the full url will be `print(f"{URLs.IMDB}.tgz")`

and you can try the direct link that doesn't need DNS, I translated it for you:
http://67.205.15.147/data/examples/imdb_sample.tgz
which should work.

the fix your dns and everything will be good.

**Comment by rbarman** [comment]
For anyone in the future who has the same issue in a Kaggle kernal, you need to turn on internet and gpu. Refer to this [previous fast ai thread](https://forums.fast.ai/t/ive-encountered-this-error-please-help-me-out/39231/4) for more info.

**Comment by quoniammm** [comment]
@rbarman i also meet this. i solved it by hand.

```c++
# the download data dir of fastai
cd ~/.fastai/data/ 
 wget http://files.fast.ai/data/examples/imdb_sample.tgz
```

you can try it.
