### ISSUE TITLE
typo in variable name n_iter

### ISSUE THREAD

**Issue by bipin2295** [fastai/course-v3#408]
```
#export
class TrainEvalCallback(Callback):
    def begin_fit(self):
        self.run.n_epochs=0.
        self.run.n_iter=0
    
    def after_batch(self):
        if not self.in_train: return
        self.run.n_epochs += 1./self.iters # should be self.iter
        self.run.n_iter   += 1
```

**Comment by siddhant2001** [comment]
can you please mention the location of this code?

**Comment by bipin2295** [comment]
In notebook 04_callback, where class TrainEvalCallback is defined.

**Comment by jph00** [comment]
Would you be interested in submitting a PR?

**Comment by g13e** [comment]
to me the code actually looks correct, it is adding 1/iters to the current epoc so that over "iters" iterations it will add increase the epochs count to 1. so this issue looks invalid to me

**Comment by mbant** [comment]
I agree with @g13e , in particular that parameter is set a couple of cells below in the Runner as
`self.iters = len(dl)`.

In the `TrainEvalCallback` it shouldn't refer to either `self.n_iter` (which points to the **current** iteration, rather than the total number) nor to `self.iter` (that doesn't exist) as the comment seems to suggest.

I can see why it could be confused though, would it be better to rename `iters` to `tot_iters` or something similar? Probably not a change that would affect this notebook only though...

**Comment by jph00** [comment]
Many thanks!
